### ISSUE TITLE
Where to get support?

### ISSUE THREAD

**Issue by iahung2** [dbsoft/dwindows#25]
Posting on the forum will get reply more quickly? I very doubt it. The forum is not any more active than this repository.

**Comment by dbsoft** [comment]
I was out of town and then temporarily locked out of github due to 2 factor authentication.  

My personal forum https://dbsoft.org/forum/ or email brian@dbsoft.org are the fastest ways... github I don't check all the time... I just use this for additional exposure, since I am not really a big fan of the site.  

I am also active on the pale moon forum since that is the other major project I work on.
