### ISSUE TITLE
`GDK_WINDOWING_WIN32` is broken

### ISSUE THREAD

**Issue by iahung2** [dbsoft/dwindows#9]
Is `GDK_WINDOWING_WIN32` ever something serious? It's broken on source level. If you build with GTK on Windows, it still drags the header `dlfcn.h` and using `dlopen` and friends. Even the comment on `dwconfig.h` is `Uses GTK but not on X11 or Wayland`, the X11 headers are still being dragged in.

I suggest if it has never worked, just remove it completely.

**Comment by dbsoft** [comment]
It did work at one point. but Mark was using it, I have focused on native. so the Win32 API.  It should probably be removed since it is likely broken. However I believe it is only in the GTK2 version and that is on the way out.  

I really recommend using the native tools for the platform, so MSVC on Windows. GCC on Linux, Clang on Mac and FreeBSD. 

I support other compilers to some degree because I like testing with more than one to find code errors and such. 

There is probably still a lot of cruft in the GTK2 code, since it started as GTK1 and transition to GTK2... but I am just leaving that in for legacy systems... I support back to Windows 2000, MacOS 10.5 and OS/2.   I don't know if it is really worth putting in the time to remove it since it is in the legacy versions.

**Comment by dbsoft** [comment]
Actually looking at it, I must have already removed that from the GTK2 source... it is just left in the header... I'll remove that for the next version.

**Comment by iahung2** [comment]
`gtk3/dw.c` also has `GDK_WINDOWING_WIN32`.

**Comment by dbsoft** [comment]
Yeah, but it is just header #ifdefs

**Comment by dbsoft** [comment]
Removed remnants of GTK on Windows from the system so closing this.
